### ISSUE TITLE
Add styled-components in the project

### ISSUE THREAD

**Issue by guilhermespopolin** [guilhermespopolin/iguitinition#2]
#### Description
Install dependencies and make changes in order to get _styled-components_ library installed in the project.

#### Screenshots
![Ohh shit](https://media.giphy.com/media/6uGhT1O4sxpi8/giphy.gif)

#### Files
* _index.js_ -> add `injectGlobal` _styled-components_ feature
* src/theme/index.js -> add _styled-components_ theme supporting

#### To Reproduce
_NA_

#### Tasks
- [ ] Add _styled-components_ as a dependency (`yarn add styled-components`)
- [ ] Research and make necessary changes in order to enable unit tests on _styled-components_
- [ ] Change project structure in order to use `injectGlobal` and theme supporting
